import {Theme, ThemeKey} from '@mattermost/types/theme';

export const THEMES: Record<ThemeKey, Theme> = {
    chicmic: {
        type: 'Chicmic',
            sidebarBg: '#1e325c',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#A8A4A2',
            sidebarTextActiveBorder: '#5d89ea',
            sidebarTextActiveColor: '#ff8750',
            sidebarHeaderBg: '#fe8751',
            sidebarHeaderTextColor: '#333333',
            sidebarTeamBarBg: '#14213e',
            onlineIndicator: '#3db887',
            awayIndicator: '#ffbc1f',
            dndIndicator: '#d24b4e',
            mentionBg: '#ffffff',
            mentionColor: 'black',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#3f4350',
            newMessageSeparator: '#cc8f00',
            linkColor: '#386fe5',
            buttonBg: '#1c58d9',
            buttonColor: '#ffffff',
            errorTextColor: '#d24b4e',
            mentionHighlightBg: '#ffd470',
            mentionHighlightLink: '#1b1d22',
            codeTheme: 'github',
    },
};
